schema_version = "1.0.0"

id = "wynns_toolkits"
version = "1.5.0"
name = "Wynn's Toolkits"
tagline = "Collection of tools for projects"
maintainer = "suthiphan khamnong"
type = "add-on"
website = "https://github.com/lolwinnerlol/Wynn-sToolKits"
tags = ["Animation", "Rigging", "Modeling"]

blender_version_min = "4.2.0"
license = ["GPL-2.0-or-later"]
copyright = "2024 suthiphan khamnong"

[permissions]
network = { optional = true }
files = { optional = true }
clipboard = { optional = true }